- name: sleeping hours
  fields:
    - name: hours
      type: integer
      title: How many hours have I slept today?
    - name: feeling_good
      type: integer
      title: How am I feeling well (from 1 to 10)?
  notifications:
    - at: "12:00"
      message: "add record to diary about your previous day"
      type: "notify-send"
